/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as WhalesRouteImport } from './routes/whales'
import { Route as TokenAddressRouteImport } from './routes/token.$address'
import { Route as WalletAddressRouteImport } from './routes/wallet.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const WhalesRoute = WhalesRouteImport.update({
  id: '/whales',
  path: '/whales',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenAddressRoute = TokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletAddressRoute = WalletAddressRouteImport.update({
  id: '/wallet/$address',
  path: '/wallet/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/explorer': typeof ExplorerRoute
  '/recover': typeof RecoverRoute
  '/tokens': typeof TokensRoute
  '/whales': typeof WhalesRoute
  '/token/$address': typeof TokenAddressRoute
  '/wallet/$address': typeof WalletAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/explorer': typeof ExplorerRoute
  '/recover': typeof RecoverRoute
  '/tokens': typeof TokensRoute
  '/whales': typeof WhalesRoute
  '/token/$address': typeof TokenAddressRoute
  '/wallet/$address': typeof WalletAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/explorer': typeof ExplorerRoute
  '/recover': typeof RecoverRoute
  '/tokens': typeof TokensRoute
  '/whales': typeof WhalesRoute
  '/token/$address': typeof TokenAddressRoute
  '/wallet/$address': typeof WalletAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/explorer'
    | '/recover'
    | '/tokens'
    | '/whales'
    | '/token/$address'
    | '/wallet/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/explorer'
    | '/recover'
    | '/tokens'
    | '/whales'
    | '/token/$address'
    | '/wallet/$address'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/explorer'
    | '/recover'
    | '/tokens'
    | '/whales'
    | '/token/$address'
    | '/wallet/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ExplorerRoute: typeof ExplorerRoute
  RecoverRoute: typeof RecoverRoute
  TokensRoute: typeof TokensRoute
  WhalesRoute: typeof WhalesRoute
  TokenAddressRoute: typeof TokenAddressRoute
  WalletAddressRoute: typeof WalletAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whales': {
      id: '/whales'
      path: '/whales'
      fullPath: '/whales'
      preLoaderRoute: typeof WhalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$address': {
      id: '/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof TokenAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$address': {
      id: '/wallet/$address'
      path: '/wallet/$address'
      fullPath: '/wallet/$address'
      preLoaderRoute: typeof WalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ExplorerRoute: ExplorerRoute,
  RecoverRoute: RecoverRoute,
  TokensRoute: TokensRoute,
  WhalesRoute: WhalesRoute,
  TokenAddressRoute: TokenAddressRoute,
  WalletAddressRoute: WalletAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
